version: '3'
services:
  wine-grafana:
    image: grafana/grafana-enterprise
    container_name: wine-grafana
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
    networks:
      wr_network:
        aliases:
          - winegrafana

  wine-prom:
    image: prom/prometheus
    container_name: wine-prom
    hostname: prom
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROM_DATA_PATH}:/prometheus
    networks:
      wr_network:
        aliases:
          - wineprometheus

networks:
  wr_network:
    external:
      name: wr_network